### ISSUE TITLE
Problem installing AP Downloader/Installer 1.1.3.0

### ISSUE THREAD

**Issue by tw4083** [shipsaw/AP-Downloader#3]
Hi Paul,

When trying to install the programme I get the following message:

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

And it will not let me go any further. I have also tried older versions and get the same error. I am running Windows 11 if that makes a difference.

Any help with this would be greatly appreciated.

Kind Regards

Andy

**Comment by shipsaw** [comment]
I believe I need to update the certificate, let me get on that and I'll get back to you

**Comment by shipsaw** [comment]
Hey @tw4083, I've gotten updated certificates, give the 1.1.4 release a try

**Comment by tw4083** [comment]
Hi Paul,

That is working spot on. Thanks for sorting it so quickly.

Kind Regards

Andy
