### ISSUE TITLE
Install Certificate Issue (V1.1.4)

### ISSUE THREAD

**Issue by nymr1** [shipsaw/AP-Downloader#6]
Hi Paul.

I am having issues trying to install V1.1.4. It is coming up with this error: 

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

Cheers, Jake.

**Comment by shipsaw** [comment]
Hey Jake,

Sorry about this, I'm trying to figure out a way forward as the certs just expired, and because of new requirements they now are over $300 a year to renew.  I'm going to try to get a version out that you can run without certs

**Comment by nymr1** [comment]
Ouch, lets hope its not too difficult haha.

**Comment by shipsaw** [comment]
Jake,

I'm releasing a zipped version that should work; No longer is it a windows installer, instead you just unzip it into a folder and run ApDownloader.exe.  If you don't have the net 6 runtime installed it'll prompt you, I could include it but then the download would be over 100 mb..
https://github.com/shipsaw/AP-Downloader/releases/tag/1.1.5
 
I tested this on a fresh windows install; it seems to work but if you have any problems reach out and we'll see if we can't get this sorted.

Thanks!
- Paul

**Comment by nymr1** [comment]
Star, thank you very much Paul.
